microservice-chart: &microservice-chart
  namespace: "bizevents"
  nameOverride: ""
  fullnameOverride: ""
  image:
    repository: ghcr.io/pagopa/pagopa-biz-events-datastore
    tag: "0.11.17-9-try-unorder-p"
    pullPolicy: Always
  # https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script.WebHost/Controllers/HostController.cs
  livenessProbe:
    httpGet:
      path: /info
      port: 80
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /info
      port: 80
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 10
  deployment:
    create: true
  serviceMonitor:
    create: true
    endpoints:
      - interval: 10s #jmx-exporter
        targetPort: 12345
        path: /metrics
  ports:
    - 80 #http
    - 12345 #jmx-exporter
  service:
    type: ClusterIP
    ports:
      - 80 #http
      - 12345 #jmx-exporter
  ingress: &ingress
    create: true
    host: "weudev.bizevents.internal.dev.platform.pagopa.it"
    path: /pagopa-biz-events-datastore-service/(.*)
    servicePort: 80
  serviceAccount:
    create: false
    annotations: {}
    name: ""
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
  resources: &resources
    requests:
      memory: "512Mi"
      cpu: "0.5"
    limits:
      memory: "1024Mi"
      cpu: "0.7"
  autoscaling:
    enable: true
    minReplica: 1
    maxReplica: 1
    pollingInterval: 10 # seconds
    cooldownPeriod: 50 # seconds
    triggers:
      - type: cpu
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "80"
      - type: memory
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "80"
  fileConfig: {}
  envConfig: &envConfig
    WEBSITE_SITE_NAME: "pagopabizeventsdatastore" # required to show cloud role name in application insights
    FUNCTIONS_WORKER_RUNTIME: "java"
    COSMOS_DB_NAME: "db"
    COSMOS_DB_CONTAINER_NAME: "biz-events"
    COSMOS_DB_URI: "https://pagopa-d-weu-bizevents-ds-cosmos-account.documents.azure.com:443/"
    EVENT_HUB_NAME: "nodo-dei-pagamenti-biz-evt"
    EVENT_HUB_SENDER: "pagopa-biz-evt-tx"
    PM_CLIENT_HOST: "https://api.dev.platform.pagopa.it"
    PM_GET_PAYMENT_DETAILS: "/payment-manager/events/v1/payment-events/%s"
    ENABLE_CLIENT_RETRY: "false" # enable/disable the exponential retry feature on the client
    INITIAL_INTERVAL_MILLIS: "500"
    MAX_ELAPSED_TIME_MILLIS: "1000"
    MAX_INTERVAL_MILLIS: "1000"
    MULTIPLIER: "1.5"
    RANDOMIZATION_FACTOR: "0.5"
    MAX_RETRY_ON_TRIGGER_ATTEMPTS: "1"
    TRIGGER_SCHEDULE: "0 0 5 31 2 ?" # means disable
    TRIGGER_CUSTOM_ERROR_MESSAGE: "-"
    TRIGGER_SQL_QUERY: "select TOP 1000 * from Items r where (r.eventStatus = 'FAILED' and r.version = '2' and (NOT IS_DEFINED(r.eventTriggeredBySchedule) or r.eventTriggeredBySchedule = false)) or (r.eventStatus = 'NA' and r.version = '2') or (r.eventStatus = 'RETRY' and r.version = '2' and r.eventRetryEnrichmentCount >= 0) order by r.paymentInfo.paymentDateTime ASC"
    VIEW_TRIGGER_SCHEDULE: "-" # means disable
    VIEW_TRIGGER_SQL_QUERY: "select TOP 1000 * FROM c WHERE c.eventStatus = 'DONE' and c.timestamp < DateTimeToTimestamp('2024-04-24T16:00:00') order by c.timestamp DESC" # DESC to process the newest entries first
    REDIS_PORT: "6380"
    REDIS_EXPIRE_TIME_MS: "3600000" # an hour
    ENABLE_TRANSACTION_LIST_VIEW: "true"
    TIMER_TRIGGER_ENABLE_TRANSACTION_LIST_VIEW: "false"
  envFieldRef: &envFieldRef
    APP_NAME: "metadata.labels['app.kubernetes.io/instance']"
    APP_VERSION: "metadata.labels['app.kubernetes.io/version']"
  envSecret: &envSecret
    APPLICATIONINSIGHTS_CONNECTION_STRING: 'ai-d-connection-string'
    EVENTHUB_CONN_STRING: 'ehub-d-biz-connection-string'
    PDND_EVENTHUB_CONN_STRING: 'ehub-d-biz-enrich-connection-string'
    COSMOS_CONN_STRING: 'cosmos-d-biz-connection-string'
    EVENT_HUB_TX_PRIMARY_KEY: 'ehub-tx-d-biz-key'
    COSMOS_DB_PRIMARY_KEY: 'cosmos-d-biz-key'
    PM_API_KEY: 'payment-manager-subscription-key' # Ocp-Apim-Subscription-Key
    AzureWebJobsStorage: 'bizevent-d-azurewebjobsstorage'
    REDIS_PWD: 'redis-password'
    REDIS_HOST: 'redis-hostname'
    PDV_TOKENIZER_SUBSCRIPTION_KEY: "tokenizer-api-key"
  keyvault:
    name: "pagopa-d-bizevents-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: {}
  tolerations: []
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - "user"
  canaryDelivery:
    create: false
    deployment:
      create: false
      image:
        tag: 0.5.6
  create: false
# 1 - datastore instance
pagopa-biz-events-datastore:
  !!merge <<: *microservice-chart
  ingress:
    !!merge <<: *ingress
  resources:
    !!merge <<: *resources
  envConfig:
    !!merge <<: *envConfig
    AzureWebJobs.BizEventToViewDataStoreTimerTriggerProcessor.Disabled: "true"
  envSecret:
    !!merge <<: *envSecret
# 2 - ingesstion instance
pagopa-biz-events-ingestion:
  !!merge <<: *microservice-chart
  ingress:
    !!merge <<: *ingress
    path: /notused/(.*) 
  resources:
    !!merge <<: *resources
    requests:
      memory: "512Mi"
      cpu: "0.3"
    limits:
      memory: "1024Mi"
      cpu: "0.8"
    autoscaling:
      enable: true
      minReplica: 1
      maxReplica: 1
  envConfig:
    !!merge <<: *envConfig
    WEBSITE_SITE_NAME: 'pagopabizeventsdatastoreingestion'
    VIEW_TRIGGER_SCHEDULE: "-" # https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-timer?tabs=python-v2%2Cisolated-process%2Cnodejs-v4&pivots=programming-language-java#ncrontab-examples
    VIEW_TRIGGER_SQL_QUERY: "select TOP 10000 * FROM c" # DESC to process the newest entries first
    TIMER_TRIGGER_ENABLE_TRANSACTION_LIST_VIEW: "false"
    AzureWebJobs.BizEventEnrichmentProcessor.Disabled: "true"
    AzureWebJobs.BizEventTimerTriggerProcessor.Disabled: "true"
    AzureWebJobs.EventHubBizEventProcessor.Disabled: "true"
  envSecret:
    !!merge <<: *envSecret
