microservice-chart: &microservice-chart
  namespace: "bizevents"
  nameOverride: ""
  fullnameOverride: ""
  image:
    repository: ghcr.io/pagopa/pagopa-biz-events-datastore
    tag: "0.12.0"
    pullPolicy: Always
  # https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script.WebHost/Controllers/HostController.cs
  livenessProbe:
    httpGet:
      path: /info
      port: 8080
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /info
      port: 8080
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 10
  deployment:
    create: true
  serviceMonitor:
    create: true
    endpoints:
      - interval: 10s #jmx-exporter
        targetPort: 12345
        path: /metrics
  ports:
    - 12345 #jmx-exporter
    - 8080
  service:
    type: ClusterIP
    ports:
      - 8080
      - 12345 #jmx-exporter
  ingress: &ingress
    create: true
    host: "weudev.bizevents.internal.dev.platform.pagopa.it"
    path: /pagopa-biz-events-datastore-service/(.*)
    servicePort: 8080
  serviceAccount:
    name: "bizevents-workload-identity"
  azure:
    workloadIdentityClientId: <workload-identity-client-id-set-automatically-by-gha>
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
  resources: &resources
    requests:
      memory: "512Mi"
      cpu: "0.5"
    limits:
      memory: "1024Mi"
      cpu: "0.7"
  autoscaling:
    enable: true
    minReplica: 1
    maxReplica: 1
    pollingInterval: 10 # seconds
    cooldownPeriod: 50 # seconds
    triggers:
      - type: cpu
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "80"
      - type: memory
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "80"
  fileConfig: {}
  envConfig: &envConfig
    ASPNETCORE_URLS: "http://*:8080"
    FUNCTIONS_SECRETS_PATH: "/tmp/secrets"
    WEBSITE_SITE_NAME: "pagopabizeventsdatastore" # required to show cloud role name in application insights
    FUNCTIONS_WORKER_RUNTIME: "java"
    COSMOS_DB_NAME: "db"
    COSMOS_DB_CONTAINER_NAME: "biz-events"
    COSMOS_DB_URI: "https://pagopa-d-weu-bizevents-ds-cosmos-account.documents.azure.com:443/"
    EVENT_HUB_NAME: "nodo-dei-pagamenti-biz-evt"
    EVENT_HUB_SENDER: "pagopa-biz-evt-tx"
    PM_CLIENT_HOST: "https://api.dev.platform.pagopa.it"
    PM_GET_PAYMENT_DETAILS: "/payment-manager/events/v1/payment-events/%s"
    ENABLE_CLIENT_RETRY: "false" # enable/disable the exponential retry feature on the client
    INITIAL_INTERVAL_MILLIS: "500"
    MAX_ELAPSED_TIME_MILLIS: "1000"
    MAX_INTERVAL_MILLIS: "1000"
    MULTIPLIER: "1.5"
    RANDOMIZATION_FACTOR: "0.5"
    MAX_RETRY_ON_TRIGGER_ATTEMPTS: "1"
    TRIGGER_SCHEDULE: "0 0 5 31 2 ?" # means disable
    TRIGGER_CUSTOM_ERROR_MESSAGE: "-"
    TRIGGER_SQL_QUERY: "select TOP 1000 * from Items r where (r.eventStatus = 'FAILED' and r.version = '2' and (NOT IS_DEFINED(r.eventTriggeredBySchedule) or r.eventTriggeredBySchedule = false)) or (r.eventStatus = 'NA' and r.version = '2') or (r.eventStatus = 'RETRY' and r.version = '2' and r.eventRetryEnrichmentCount >= 0) order by r.paymentInfo.paymentDateTime ASC"
    REDIS_PORT: "6380"
    REDIS_EXPIRE_TIME_MS: "3600000" # an hour
    ENABLE_TRANSACTION_LIST_VIEW: "true" # biz trx on-line
    AUTHENTICATED_CHANNELS: "IO,CHECKOUT,CHECKOUT_CART"
    UPDATE_VIEW_TIMER_TRIGGER_ENABLE: "false"
    UPDATE_VIEW_ORIGIN_VALUE: "NDP003DEV" # https://pagopa.atlassian.net/wiki/spaces/PN5/pages/627179761/Identificativo+servizio+nodo
    UPDATE_VIEW_TRIGGER_SCHEDULE: "-" # "0 */3 * * * *" # https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-timer?tabs=python-v2%2Cisolated-process%2Cnodejs-v4&pivots=programming-language-java#ncrontab-examples
    UPDATE_VIEW_TRIGGER_SQL_QUERY: "select TOP 1000 * FROM c WHERE c.origin = 'UNKNOWN'"
  envFieldRef: &envFieldRef
    APP_NAME: "metadata.labels['app.kubernetes.io/instance']"
    APP_VERSION: "metadata.labels['app.kubernetes.io/version']"
  envSecret: &envSecret
    APPLICATIONINSIGHTS_CONNECTION_STRING: 'ai-d-connection-string'
    EVENTHUB_CONN_STRING: 'ehub-d-biz-connection-string'
    PDND_EVENTHUB_CONN_STRING: 'ehub-d-biz-enrich-connection-string'
    VIEWS_EVENTHUB_CONN_STRING: 'ehub-views-d-biz-connection-string'
    COSMOS_CONN_STRING: 'cosmos-d-biz-connection-string'
    COSMOS_DB_PRIMARY_KEY: 'cosmos-d-biz-key'
    PM_API_KEY: 'payment-manager-subscription-key' # Ocp-Apim-Subscription-Key
    # AzureWebJobsStorage: 'bizevent-d-azurewebjobsstorage'
    REDIS_PWD: 'redis-password'
    REDIS_HOST: 'redis-hostname'
    PDV_TOKENIZER_SUBSCRIPTION_KEY: "tokenizer-api-key"
  keyvault:
    name: "pagopa-d-bizevents-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: {}
  tolerations: []
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - "user"
  canaryDelivery:
    create: false
# 1 - biz-datastore instance
pagopa-biz-events-datastore:
  !!merge <<: *microservice-chart
  ingress:
    !!merge <<: *ingress
  resources:
    !!merge <<: *resources
  envConfig:
    !!merge <<: *envConfig
    AzureWebJobs.EventHubBizEventProcessor.Disabled: "false"
    AzureWebJobs.BizEventEnrichmentProcessor.Disabled: "true"
    AzureWebJobs.BizEventTimerTriggerProcessor.Disabled: "true"
    AzureWebJobs.BizEventToViewDataStoreTimerTriggerProcessor.Disabled: "true"
    AzureWebJobs.BizEventViewDataStoreUpdateTimerTriggerProcessor.Disabled: "true"
    AzureWebJobs.BizEventToView.Disabled: "false"
  envSecret:
    !!merge <<: *envSecret
    AzureWebJobsStorage: 'bizevent-d-azurewebjobsstorage'
# 2 - biz-view instance    
pagopa-biz-events-view:
  !!merge <<: *microservice-chart
  ingress:
    !!merge <<: *ingress
    path: /notused-biz-view/(.*)
  resources:
    !!merge <<: *resources
  envConfig:
    !!merge <<: *envConfig
    WEBSITE_SITE_NAME: 'pagopabizeventsdatastoreview'
    AzureWebJobs.EventHubBizEventProcessor.Disabled: "true"
    AzureWebJobs.BizEventEnrichmentProcessor.Disabled: "false"
    AzureWebJobs.BizEventTimerTriggerProcessor.Disabled: "true"
    AzureWebJobs.BizEventToViewDataStoreTimerTriggerProcessor.Disabled: "true"
    AzureWebJobs.BizEventViewDataStoreUpdateTimerTriggerProcessor.Disabled: "true"
    AzureWebJobs.BizEventToView.Disabled: "true"
  envSecret:
    !!merge <<: *envSecret
    AzureWebJobsStorage: 'bizevent-view-d-azurewebjobsstorage'
    # 2 - ingesstion instance
    # pagopa-biz-events-ingestion:
    #   !!merge <<: *microservice-chart
    #   ingress:
    #     !!merge <<: *ingress
    #     path: /notused/(.*)
    #   resources:
    #     !!merge <<: *resources
    #     requests:
    #       memory: "512Mi"
    #       cpu: "0.3"
    #     limits:
    #       memory: "512Mi"
    #       cpu: "0.3"
    #     autoscaling:
    #       enable: true
    #       minReplica: 1
    #       maxReplica: 1
    #   envConfig:
    #     !!merge <<: *envConfig
    #     WEBSITE_SITE_NAME: 'pagopabizeventsdatastoreingestion'
    #     VIEW_TRIGGER_SCHEDULE: "-" # "0 */3 * * * *" # https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-timer?tabs=python-v2%2Cisolated-process%2Cnodejs-v4&pivots=programming-language-java#ncrontab-examples
    #     TIMER_TRIGGER_ENABLE_TRANSACTION_LIST_VIEW: "false"
    #     AzureWebJobs.BizEventEnrichmentProcessor.Disabled: "true"
    #     AzureWebJobs.BizEventTimerTriggerProcessor.Disabled: "true"
    #     AzureWebJobs.EventHubBizEventProcessor.Disabled: "true"
    #     AzureWebJobs.BizEventToViewDataStoreTimerTriggerProcessor.Disabled: "true" # To enable for Ingestion
    #     AzureWebJobs.BizEventViewDataStoreUpdateTimerTriggerProcessor.Disabled: "true"
    #   envSecret:
    #     !!merge <<: *envSecret
    #     VIEW_TRIGGER_SQL_QUERY: 'cosmos-d-biz-view-trigger-sql-query-string'
    # 3 - update instance view
    # pagopa-biz-events-update-view:
    #   !!merge <<: *microservice-chart
    #   ingress:
    #     !!merge <<: *ingress
    #     path: /notused-2/(.*)
    #   resources:
    #     !!merge <<: *resources
    #     requests:
    #       memory: "512Mi"
    #       cpu: "0.3"
    #     limits:
    #       memory: "1024Mi"
    #       cpu: "0.5"
    #     autoscaling:
    #       enable: true
    #       minReplica: 1
    #       maxReplica: 1
    #   envConfig:
    #     !!merge <<: *envConfig
    #     WEBSITE_SITE_NAME: 'pagopabizeventsdatastoreupdateview'
    #     UPDATE_VIEW_TIMER_TRIGGER_ENABLE: "false"
    #     UPDATE_VIEW_ORIGIN_VALUE: "NDP003DEV" # https://pagopa.atlassian.net/wiki/spaces/PN5/pages/627179761/Identificativo+servizio+nodo
    #     UPDATE_VIEW_TRIGGER_SCHEDULE: "-" # "0 */3 * * * *" # https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-timer?tabs=python-v2%2Cisolated-process%2Cnodejs-v4&pivots=programming-language-java#ncrontab-examples
    #     UPDATE_VIEW_TRIGGER_SQL_QUERY: "select TOP 1000 * FROM c WHERE c.origin = 'UNKNOWN'"
    #     AzureWebJobs.BizEventEnrichmentProcessor.Disabled: "true"
    #     AzureWebJobs.BizEventTimerTriggerProcessor.Disabled: "true"
    #     AzureWebJobs.EventHubBizEventProcessor.Disabled: "true"
    #     AzureWebJobs.BizEventToViewDataStoreTimerTriggerProcessor.Disabled: "true"
