microservice-chart:
  namespace: "bizevents"
  nameOverride: ""
  fullnameOverride: ""
  image:
    repository: ghcr.io/pagopa/pagopa-biz-events-datastore
    tag: "0.11.5-1-tmp-try#1"
    pullPolicy: Always
  # https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script.WebHost/Controllers/HostController.cs
  livenessProbe:
    httpGet:
      path: /info
      port: 80
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /info
      port: 80
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 10
  deployment:
    create: true
  serviceMonitor:
    create: true
    endpoints:
      - interval: 10s #jmx-exporter
        targetPort: 12345
        path: /metrics
  ports:
    - 80 #http
    - 12345 #jmx-exporter
  service:
    type: ClusterIP
    ports:
      - 80 #http
      - 12345 #jmx-exporter
  ingress:
    create: true
    host: "weuprod.bizevents.internal.platform.pagopa.it"
    path: /pagopa-biz-events-datastore-service/(.*)
    servicePort: 80
  serviceAccount:
    create: false
    annotations: {}
    name: ""
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
  resources:
    requests:
      memory: "1024Mi"
      cpu: "0.8"
    limits:
      memory: "1536Mi"
      cpu: "1.0"
  autoscaling:
    enable: true
    minReplica: 2
    maxReplica: 10
    pollingInterval: 10 # seconds
    cooldownPeriod: 50 # seconds
    triggers:
      - type: cpu
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "75"
      - type: memory
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "70"
  fileConfig: {}
  envConfig:
    WEBSITE_SITE_NAME: "pagopabizeventsdatastore" # required to show cloud role name in application insights
    FUNCTIONS_WORKER_RUNTIME: "java"
    COSMOS_DB_NAME: "db"
    COSMOS_DB_CONTAINER_NAME: "biz-events"
    COSMOS_DB_URI: "https://pagopa-p-weu-bizevents-ds-cosmos-account.documents.azure.com:443/"
    EVENT_HUB_NAMESPACE: "pagopa-p-evh-ns01"
    EVENT_HUB_NAME: "nodo-dei-pagamenti-biz-evt"
    EVENT_HUB_SENDER: "pagopa-biz-evt-tx"
    PM_CLIENT_HOST: "https://api.platform.pagopa.it"
    PM_GET_PAYMENT_DETAILS: "/payment-manager/events/v1/payment-events/%s"
    ENABLE_CLIENT_RETRY: "false" # enable/disable the exponential retry feature on the client
    INITIAL_INTERVAL_MILLIS: "500"
    MAX_ELAPSED_TIME_MILLIS: "1000"
    MAX_INTERVAL_MILLIS: "1000"
    MULTIPLIER: "1.5"
    RANDOMIZATION_FACTOR: "0.5"
    MAX_RETRY_ON_TRIGGER_ATTEMPTS: "1"
    TRIGGER_SCHEDULE: "0 0 5 31 2 ?" # means disable
    TRIGGER_CUSTOM_ERROR_MESSAGE: "errore"
    TRIGGER_SQL_QUERY: "select TOP 3000 * from Items r where r.eventStatus != 'DONE' order by r._ts ASC"
    REDIS_HOST: "pagopa-p-redis.redis.cache.windows.net"
    REDIS_PORT: "6380"
    REDIS_EXPIRE_TIME_MS: "3600000" # an hour
    PDV_TOKENIZER_BASE_PATH: "https://api.tokenizer.pdv.pagopa.it/tokenizer/v1"
    PDV_TOKENIZER_INITIAL_INTERVAL: "550"
    PDV_TOKENIZER_MULTIPLIER: "1.5"
    PDV_TOKENIZER_RANDOMIZATION_FACTOR: "0.6"
    PDV_TOKENIZER_MAX_RETRIES: "5"
    ENABLE_TRANSACTION_LIST_VIEW: "false"
  envFieldRef:
    APP_NAME: "metadata.labels['app.kubernetes.io/instance']"
    APP_VERSION: "metadata.labels['app.kubernetes.io/version']"
  envSecret:
    APPLICATIONINSIGHTS_CONNECTION_STRING: 'ai-p-connection-string'
    EVENTHUB_CONN_STRING: 'ehub-p-biz-connection-string'
    PDND_EVENTHUB_CONN_STRING: 'ehub-p-biz-enrich-connection-string'
    COSMOS_CONN_STRING: 'cosmos-p-biz-connection-string'
    EVENT_HUB_TX_PRIMARY_KEY: 'ehub-tx-p-biz-key'
    COSMOS_DB_PRIMARY_KEY: 'cosmos-p-biz-key'
    PM_API_KEY: 'payment-manager-subscription-key' # Ocp-Apim-Subscription-Key
    AzureWebJobsStorage: 'bizevent-p-azurewebjobsstorage'
    REDIS_PWD: "redis-password"
    PDV_TOKENIZER_SUBSCRIPTION_KEY: "tokenizer-api-key"
  keyvault:
    name: "pagopa-p-bizevents-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: {}
  tolerations: []
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - user
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/instance: pagopabizeventsdatastore
            namespaces: ["bizevents"]
            topologyKey: topology.kubernetes.io/zone
  canaryDelivery:
    create: false
    deployment:
      create: false
      image:
        tag: 0.5.6
  create: false
